-- Generated by describe_columns.py. Run in the Blue Dots project.
-- Puts each column's provenance where someone browsing the table
-- in Supabase will actually see it.

comment on column public.kkb_mastersheet.id is
    'database default. Not in the row builder at all - a serial id or a default the database supplies. Expression: -';
comment on column public.kkb_mastersheet.campaign_name is
    'computed locally. Derived by our code. Ours to change. Expression: campaign_name';
comment on column public.kkb_mastersheet.jfc_campaign is
    'computed locally. Derived by our code. Ours to change. Expression: jfc';
comment on column public.kkb_mastersheet.bot_language is
    'filled by a backfill. The row builder leaves this null; a backfill script fills it afterwards. It goes stale if the backfill is not re-run after new rows land. Expression: None';
comment on column public.kkb_mastersheet.test_flag is
    'filled by a backfill. The row builder leaves this null; a backfill script fills it afterwards. It goes stale if the backfill is not re-run after new rows land. Expression: None';
comment on column public.kkb_mastersheet.phone_number is
    'computed locally. Derived by our code. Ours to change. Expression: str(phone) if phone is not None else None';
comment on column public.kkb_mastersheet.source_id is
    'database default. Not in the row builder at all - a serial id or a default the database supplies. Expression: -';
comment on column public.kkb_mastersheet.seeker_name is
    'computed locally. Derived by our code. Ours to change. Expression: name';
comment on column public.kkb_mastersheet.recommendations_input is
    'computed locally. Derived by our code. Ours to change. Expression: recommendations_input';
comment on column public.kkb_mastersheet.call_duration_seconds is
    'Raya · call record. Recorded by the dialler. Fact. Expression: safe_float(call.get(''call_duration''))';
comment on column public.kkb_mastersheet.call_recording_url is
    'Raya · call record. Recorded by the dialler. Fact. Expression: recording_url or call.get(''call_recording_url'') or None';
comment on column public.kkb_mastersheet.call_transcript is
    'Raya · transcript. Dug out of the conversation and its tool calls. A tool call either happened or it did not, so this is the strongest evidence we have. Expression: transcript_text';
comment on column public.kkb_mastersheet.call_summary is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: call_output.get(''final_summary'') or call_output.get(''call_summary'') or None';
comment on column public.kkb_mastersheet.call_outcome is
    'Raya · call record. Recorded by the dialler. Fact. Expression: contact.get(''status'') or call_output.get(''outcome'') or None';
comment on column public.kkb_mastersheet.drop_reasom is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: call_output.get(''drop_reason'') or None';
comment on column public.kkb_mastersheet.call_answered is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: safe_bool(call_output.get(''call_answered''))';
comment on column public.kkb_mastersheet.call_engaged is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: safe_bool(call_output.get(''call_engaged''))';
comment on column public.kkb_mastersheet.create_profile_api_success is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.kkb_mastersheet.jobs_shown is
    'computed locally. Derived by our code. Ours to change. Expression: bool(jobs_recommended) if jobs_recommended is not None else None';
comment on column public.kkb_mastersheet.jobs_mismatch is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.kkb_mastersheet.applied_to_job is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: safe_bool(call_output.get(''applied_to_job''))';
comment on column public.kkb_mastersheet.apply_api_success is
    'computed locally. Derived by our code. Ours to change. Expression: apply_api_success';
comment on column public.kkb_mastersheet.needs_mentioned is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.kkb_mastersheet.needs_details is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.kkb_mastersheet.applications_count is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: safe_int(call_output.get(''applications_count''))';
comment on column public.kkb_mastersheet.intent_score is
    'computed locally. Derived by our code. Ours to change. Expression: float(intent_score)';
comment on column public.kkb_mastersheet.intent_score_reasoning is
    'computed locally. Derived by our code. Ours to change. Expression: intent_score_reasoning';
comment on column public.kkb_mastersheet.jobs_recommended is
    'computed locally. Derived by our code. Ours to change. Expression: jobs_recommended';
comment on column public.kkb_mastersheet.jobs_applied is
    'computed locally. Derived by our code. Ours to change. Expression: jobs_applied';
comment on column public.kkb_mastersheet.profile_completeness is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: safe_float(call_output.get(''profile_completeness''))';
comment on column public.kkb_mastersheet.profile_correctness is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: safe_float(call_output.get(''profile_correctness''))';
comment on column public.kkb_mastersheet.new_seeker_id is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.kkb_mastersheet.phone is
    'computed locally. Derived by our code. Ours to change. Expression: str(phone) if phone is not None else None';
comment on column public.kkb_mastersheet.name is
    'computed locally. Derived by our code. Ours to change. Expression: name';
comment on column public.kkb_mastersheet.gender is
    'filled by a backfill. The row builder leaves this null; a backfill script fills it afterwards. It goes stale if the backfill is not re-run after new rows land. Expression: None';
comment on column public.kkb_mastersheet.role is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.kkb_mastersheet.workExperience is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.kkb_mastersheet.workExperienceYears is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.kkb_mastersheet.highestQualification is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.kkb_mastersheet.natureOfJobsInterestedIn is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.kkb_mastersheet.campaign_day is
    'Raya · call record. Recorded by the dialler. Fact. Expression: campaign_day_number(batch, call_date)';
comment on column public.kkb_mastersheet.call_id is
    'Raya · call record. Recorded by the dialler. Fact. Expression: str(contact.get(''contact_id'')) if contact.get(''contact_id'') is not None else None';
comment on column public.kkb_mastersheet.campaign_date is
    'Raya · call record. Recorded by the dialler. Fact. Expression: call_date.isoformat() if call_date else None';
comment on column public.kkb_mastersheet.channel is
    'computed locally. Derived by our code. Ours to change. Expression: ''Outbound''';
comment on column public.kkb_mastersheet.agent_id is
    'computed locally. Derived by our code. Ours to change. Expression: str(agent_id) if agent_id else None';
comment on column public.kkb_mastersheet.agent_name is
    'computed locally. Derived by our code. Ours to change. Expression: agent_name';
comment on column public.kkb_mastersheet.batch_id is
    'computed locally. Derived by our code. Ours to change. Expression: str(batch_id) if batch_id is not None else None';
comment on column public.kkb_mastersheet.jobs_failed_to_apply is
    'computed locally. Derived by our code. Ours to change. Expression: jobs_failed_to_apply';
comment on column public.kkb_mastersheet.apply_attempts is
    'Raya · transcript. Dug out of the conversation and its tool calls. A tool call either happened or it did not, so this is the strongest evidence we have. Expression: extract_apply_attempts(raw_transcript)';
comment on column public.kkb_mastersheet.college_name is
    'Raya · agent_args. What WE sent the bot when the batch was made. Echoed back unchanged. Expression: normalise_college(agent_args.get(''college_name''))';

comment on column public.dkb_mastersheet.call_id is
    'Raya · call record. Recorded by the dialler. Fact. Expression: str(contact.get(''contact_id'')) if contact.get(''contact_id'') is not None else None';
comment on column public.dkb_mastersheet.campaign_day is
    'computed locally. Derived by our code. Ours to change. Expression: campaign_day';
comment on column public.dkb_mastersheet.campaign_name is
    'computed locally. Derived by our code. Ours to change. Expression: from_any_call(contact, ''campaign_type'')';
comment on column public.dkb_mastersheet.jfc_campaign is
    'computed locally. Derived by our code. Ours to change. Expression: jfc';
comment on column public.dkb_mastersheet.call_datetime_ist is
    'computed locally. Derived by our code. Ours to change. Expression: ist_datetime(call)';
comment on column public.dkb_mastersheet.test_flag is
    'filled by a backfill. The row builder leaves this null; a backfill script fills it afterwards. It goes stale if the backfill is not re-run after new rows land. Expression: None';
comment on column public.dkb_mastersheet.contact_phone is
    'computed locally. Derived by our code. Ours to change. Expression: str(phone) if phone else None';
comment on column public.dkb_mastersheet.job_id is
    'Raya · agent_args. What WE sent the bot when the batch was made. Echoed back unchanged. Expression: clean(args.get(''job_id'')) or clean(call_output.get(''job_id''))';
comment on column public.dkb_mastersheet.source_id is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.dkb_mastersheet.company_name is
    'Raya · agent_args. What WE sent the bot when the batch was made. Echoed back unchanged. Expression: clean(args.get(''company_name'')) or clean(call_output.get(''company_name''))';
comment on column public.dkb_mastersheet.job_role_input is
    'Raya · agent_args. What WE sent the bot when the batch was made. Echoed back unchanged. Expression: clean(args.get(''job_role''))';
comment on column public.dkb_mastersheet.city_input is
    'Raya · agent_args. What WE sent the bot when the batch was made. Echoed back unchanged. Expression: clean(args.get(''city''))';
comment on column public.dkb_mastersheet.location_input is
    'Raya · agent_args. What WE sent the bot when the batch was made. Echoed back unchanged. Expression: clean(args.get(''location''))';
comment on column public.dkb_mastersheet.salary_input is
    'Raya · agent_args. What WE sent the bot when the batch was made. Echoed back unchanged. Expression: clean(args.get(''salary''))';
comment on column public.dkb_mastersheet.qualification_input is
    'Raya · agent_args. What WE sent the bot when the batch was made. Echoed back unchanged. Expression: clean(args.get(''qualification''))';
comment on column public.dkb_mastersheet.call_duration is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.dkb_mastersheet.call_recording_url is
    'computed locally. Derived by our code. Ours to change. Expression: recording_url';
comment on column public.dkb_mastersheet.call_transcript is
    'Raya · transcript. Dug out of the conversation and its tool calls. A tool call either happened or it did not, so this is the strongest evidence we have. Expression: dkb_transcript(raw_transcript)';
comment on column public.dkb_mastersheet.call_summary is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: clean(call_output.get(''final_summary''))';
comment on column public.dkb_mastersheet.call_outcome is
    'computed locally. Derived by our code. Ours to change. Expression: outcome';
comment on column public.dkb_mastersheet.drop_reason is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: clean(call_output.get(''drop_reason''))';
comment on column public.dkb_mastersheet.call_status is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: clean(call_output.get(''call_status''))';
comment on column public.dkb_mastersheet.phases_reached is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: phase_number(call_output.get(''phases_reached''))';
comment on column public.dkb_mastersheet.update_api_success is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.dkb_mastersheet.update_job_status is
    'computed locally. Derived by our code. Ours to change. Expression: job_status';
comment on column public.dkb_mastersheet.other_needs_mentioned is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.dkb_mastersheet.other_needs is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.dkb_mastersheet.update_completeness is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.dkb_mastersheet.update_correctness is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.dkb_mastersheet.new_job_mentioned is
    'computed locally. Derived by our code. Ours to change. Expression: new_job_mentioned';
comment on column public.dkb_mastersheet.new_job_posted is
    'computed locally. Derived by our code. Ours to change. Expression: new_job_posted';
comment on column public.dkb_mastersheet.total_jobs_posted is
    'computed locally. Derived by our code. Ours to change. Expression: 1 if new_job_posted else 0';
comment on column public.dkb_mastersheet.intent_score is
    'computed locally. Derived by our code. Ours to change. Expression: intent_score';
comment on column public.dkb_mastersheet.intent_score_reasoning is
    'computed locally. Derived by our code. Ours to change. Expression: intent_reasoning';
comment on column public.dkb_mastersheet.updated_job_role is
    'database default. Not in the row builder at all - a serial id or a default the database supplies. Expression: -';
comment on column public.dkb_mastersheet.updated_vacancies is
    'database default. Not in the row builder at all - a serial id or a default the database supplies. Expression: -';
comment on column public.dkb_mastersheet.updated_salary is
    'database default. Not in the row builder at all - a serial id or a default the database supplies. Expression: -';
comment on column public.dkb_mastersheet.updated_location is
    'database default. Not in the row builder at all - a serial id or a default the database supplies. Expression: -';
comment on column public.dkb_mastersheet.updated_qualification is
    'database default. Not in the row builder at all - a serial id or a default the database supplies. Expression: -';
comment on column public.dkb_mastersheet.call_duration_seconds is
    'computed locally. Derived by our code. Ours to change. Expression: duration';
comment on column public.dkb_mastersheet.fields_updated is
    'computed locally. Derived by our code. Ours to change. Expression: changed';
comment on column public.dkb_mastersheet.campaign_date is
    'computed locally. Derived by our code. Ours to change. Expression: (cdate or batch_start).isoformat() if cdate or batch_start else None';
comment on column public.dkb_mastersheet.num_vacancies_input is
    'Raya · agent_args. What WE sent the bot when the batch was made. Echoed back unchanged. Expression: clean(args.get(''num_vacancies'')) or clean(call_output.get(''num_vacancies_input''))';
comment on column public.dkb_mastersheet.contact_attempts is
    'Raya · call record. Recorded by the dialler. Fact. Expression: whole_number(call_output.get(''contact_attempts'')) or safe_int(contact.get(''attempts''))';
comment on column public.dkb_mastersheet.bot_language is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: clean(call_output.get(''language''))';
comment on column public.dkb_mastersheet.contact_name is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: clean(call_output.get(''contact_name''))';
comment on column public.dkb_mastersheet.channel is
    'database default. Not in the row builder at all - a serial id or a default the database supplies. Expression: -';

comment on column public.trrain_mastersheet.id is
    'database default. Not in the row builder at all - a serial id or a default the database supplies. Expression: -';
comment on column public.trrain_mastersheet.call_id is
    'Raya · call record. Recorded by the dialler. Fact. Expression: str(contact.get(''contact_id'')) if contact.get(''contact_id'') is not None else None';
comment on column public.trrain_mastersheet.batch_id is
    'Raya · call record. Recorded by the dialler. Fact. Expression: str(batch.get(''id'')) if batch.get(''id'') is not None else None';
comment on column public.trrain_mastersheet.campaign_name is
    'Raya · call record. Recorded by the dialler. Fact. Expression: clean(batch.get(''name''))';
comment on column public.trrain_mastersheet.campaign_date is
    'Raya · call record. Recorded by the dialler. Fact. Expression: (lambda d: d.isoformat() if d else None)(call_date_ist(call))';
comment on column public.trrain_mastersheet.call_datetime_ist is
    'computed locally. Derived by our code. Ours to change. Expression: ist_datetime(call)';
comment on column public.trrain_mastersheet.agent_id is
    'computed locally. Derived by our code. Ours to change. Expression: str(agent_id) if agent_id else None';
comment on column public.trrain_mastersheet.agent_name is
    'computed locally. Derived by our code. Ours to change. Expression: agent_name';
comment on column public.trrain_mastersheet.jfc_campaign is
    'computed locally. Derived by our code. Ours to change. Expression: jfc';
comment on column public.trrain_mastersheet.channel is
    'computed locally. Derived by our code. Ours to change. Expression: ''Outbound''';
comment on column public.trrain_mastersheet.phone is
    'computed locally. Derived by our code. Ours to change. Expression: str(phone) if phone else None';
comment on column public.trrain_mastersheet.contact_name is
    'Raya · call record. Recorded by the dialler. Fact. Expression: clean(contact.get(''name''))';
comment on column public.trrain_mastersheet.seeker_name is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: clean(latest_answer(outs, ''seeker_name''))';
comment on column public.trrain_mastersheet.right_person is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: tristate(latest_answer(outs, ''right_person''))';
comment on column public.trrain_mastersheet.call_answered is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(call_output.get(''call_answered''))';
comment on column public.trrain_mastersheet.audio_check_confirmed is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: tristate(latest_answer(outs, ''audio_check_confirmed''))';
comment on column public.trrain_mastersheet.trrain_pitched is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(latest_answer(outs, ''trrain_pitched''))';
comment on column public.trrain_mastersheet.trrain_interest is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: tristate(latest_answer(outs, ''trrain_interest''))';
comment on column public.trrain_mastersheet.partner_named is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(latest_answer(outs, ''partner_named''))';
comment on column public.trrain_mastersheet.offer_repeated is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(latest_answer(outs, ''offer_repeated''))';
comment on column public.trrain_mastersheet.remembered_application is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: tristate(latest_answer(outs, ''remembered_application''))';
comment on column public.trrain_mastersheet.questions_asked is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: question_list(latest_answer(outs, ''questions_asked''))';
comment on column public.trrain_mastersheet.do_not_call is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: any_yes(outs, ''do_not_call'')';
comment on column public.trrain_mastersheet.promised_outcome is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(latest_answer(outs, ''promised_outcome''))';
comment on column public.trrain_mastersheet.callback_requested is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: clean(latest_answer(outs, ''callback_requested''))';
comment on column public.trrain_mastersheet.call_outcome is
    'Raya · call record. Recorded by the dialler. Fact. Expression: clean(call.get(''outcome''))';
comment on column public.trrain_mastersheet.call_duration_seconds is
    'Raya · call record. Recorded by the dialler. Fact. Expression: call.get(''call_duration'')';
comment on column public.trrain_mastersheet.contact_attempts is
    'Raya · call record. Recorded by the dialler. Fact. Expression: len(contact.get(''calls'') or [])';
comment on column public.trrain_mastersheet.drop_reason is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: clean(call_output.get(''drop_reason''))';
comment on column public.trrain_mastersheet.call_summary is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: clean(call_output.get(''final_summary''))';
comment on column public.trrain_mastersheet.call_transcript is
    'Raya · transcript. Dug out of the conversation and its tool calls. A tool call either happened or it did not, so this is the strongest evidence we have. Expression: raw_transcript';
comment on column public.trrain_mastersheet.call_recording_url is
    'computed locally. Derived by our code. Ours to change. Expression: recording_url';
comment on column public.trrain_mastersheet.loaded_at is
    'database default. Not in the row builder at all - a serial id or a default the database supplies. Expression: -';

comment on column public.kkb_applications.id is
    'database default. Not in the row builder at all - a serial id or a default the database supplies. Expression: -';
comment on column public.kkb_applications.call_id is
    'computed locally. Derived by our code. Ours to change. Expression: str(call_id)';
comment on column public.kkb_applications.job_id is
    'computed locally. Derived by our code. Ours to change. Expression: jid';
comment on column public.kkb_applications.applied is
    'computed locally. Derived by our code. Ours to change. Expression: ok';
comment on column public.kkb_applications.failure_reason is
    'computed locally. Derived by our code. Ours to change. Expression: None if ok else _first(errors.get(jid), job.get(''failure_reason''), ''api_failed'')';
comment on column public.kkb_applications.synthetic_job_id is
    'computed locally. Derived by our code. Ours to change. Expression: not _looks_like_uuid(jid)';
comment on column public.kkb_applications.job_role is
    'computed locally. Derived by our code. Ours to change. Expression: _first(shown.get(''role''), job.get(''role''))';
comment on column public.kkb_applications.company_name is
    'computed locally. Derived by our code. Ours to change. Expression: _first(shown.get(''company''), job.get(''company_name''))';
comment on column public.kkb_applications.provider_phone is
    'computed locally. Derived by our code. Ours to change. Expression: head if head.isdigit() else None';
comment on column public.kkb_applications.job_location is
    'computed locally. Derived by our code. Ours to change. Expression: _first(shown.get(''location''), job.get(''company_location''))';
comment on column public.kkb_applications.vacancies is
    'computed locally. Derived by our code. Ours to change. Expression: _first(shown.get(''vacancy''))';
comment on column public.kkb_applications.salary is
    'computed locally. Derived by our code. Ours to change. Expression: _first(shown.get(''salary''), job.get(''salary_offered''))';
comment on column public.kkb_applications.qualification_required is
    'computed locally. Derived by our code. Ours to change. Expression: _first(shown.get(''qualification''), job.get(''qualification_required''))';
comment on column public.kkb_applications.loaded_at is
    'database default. Not in the row builder at all - a serial id or a default the database supplies. Expression: -';
