-- Generated by describe_columns.py. Run in the Blue Dots project.
-- Puts each column's provenance where someone browsing the table
-- in Supabase will actually see it.

comment on column public.purple_dots_calls.call_id is
    'computed locally. Derived by our code. Ours to change. Expression: call_id';
comment on column public.purple_dots_calls.call_uuid is
    'Raya · call record. Recorded by the dialler. Fact. Expression: str(call.get(''uuid'')) if call.get(''uuid'') else None';
comment on column public.purple_dots_calls.batch_id is
    'Raya · call record. Recorded by the dialler. Fact. Expression: str(batch.get(''id'')) if batch.get(''id'') is not None else None';
comment on column public.purple_dots_calls.campaign_name is
    'Raya · call record. Recorded by the dialler. Fact. Expression: clean(campaign_name) or clean(batch.get(''name''))';
comment on column public.purple_dots_calls.agent_id is
    'Raya · call record. Recorded by the dialler. Fact. Expression: str(call.get(''agent_id'')) if call.get(''agent_id'') else None';
comment on column public.purple_dots_calls.agent_name is
    'computed locally. Derived by our code. Ours to change. Expression: clean(agent_name)';
comment on column public.purple_dots_calls.persona is
    'Raya · agent_args. What WE sent the bot when the batch was made. Echoed back unchanged. Expression: clean(args.get(''persona''))';
comment on column public.purple_dots_calls.channel is
    'computed locally. Derived by our code. Ours to change. Expression: ''Inbound'' if is_inbound(call) else ''Outbound''';
comment on column public.purple_dots_calls.contact_reference_type is
    'Raya · agent_args. What WE sent the bot when the batch was made. Echoed back unchanged. Expression: clean(args.get(''contact_reference_type''))';
comment on column public.purple_dots_calls.contact_reference is
    'Raya · agent_args. What WE sent the bot when the batch was made. Echoed back unchanged. Expression: clean(args.get(''contact_reference''))';
comment on column public.purple_dots_calls.call_date_ist is
    'Raya · call record. Recorded by the dialler. Fact. Expression: (lambda d: d.isoformat() if d else None)(call_date_ist(call))';
comment on column public.purple_dots_calls.call_datetime_ist is
    'Raya · call record. Recorded by the dialler. Fact. Expression: call_datetime_ist(call)';
comment on column public.purple_dots_calls.call_duration_seconds is
    'Raya · call record. Recorded by the dialler. Fact. Expression: number(call.get(''call_duration''))';
comment on column public.purple_dots_calls.contact_attempts is
    'Raya · call record. Recorded by the dialler. Fact. Expression: len(contact.get(''calls'') or []) or 1';
comment on column public.purple_dots_calls.call_status is
    'Raya · call record. Recorded by the dialler. Fact. Expression: clean(contact.get(''status'')) or OUTCOME_AS_STATUS.get(clean(call.get(''outcome'')), clean(call.get(''outcome'')))';
comment on column public.purple_dots_calls.call_answered is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(out.get(''call_answered''))';
comment on column public.purple_dots_calls.call_engaged is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(out.get(''call_engaged''))';
comment on column public.purple_dots_calls.call_dropped_abruptly is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(out.get(''call_dropped_abruptly''))';
comment on column public.purple_dots_calls.full_journey_completed is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(out.get(''full_journey_completed''))';
comment on column public.purple_dots_calls.abandoned_at_stage is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: clean(out.get(''abandoned_at_stage''))';
comment on column public.purple_dots_calls.callback_requested is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: clean(out.get(''callback_requested''))';
comment on column public.purple_dots_calls.on_behalf_of is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(out.get(''on_behalf_of''))';
comment on column public.purple_dots_calls.demographic_info_shared is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(out.get(''demographic_info_shared''))';
comment on column public.purple_dots_calls.profile_item_id is
    'Raya · transcript. Dug out of the conversation''s tool calls. The profile ids live only in the arguments the bot sent to update_profile, nowhere else. Expression: clean(prof.get(''item_id''))';
comment on column public.purple_dots_calls.profile_user_id is
    'Raya · transcript. Dug out of the conversation''s tool calls. The profile ids live only in the arguments the bot sent to update_profile, nowhere else. Expression: clean(prof.get(''user_id'') or prof.get(''acting_as_user_id''))';
comment on column public.purple_dots_calls.disability_category_mapped is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: str_list(out.get(''disability_category_mapped''))';
comment on column public.purple_dots_calls.user_unsure_disability is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(out.get(''user_unsure_disability''))';
comment on column public.purple_dots_calls.user_unsure_needs is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(out.get(''user_unsure_needs''))';
comment on column public.purple_dots_calls.solution_option_mapped_categories is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: str_list(out.get(''solution_option_mapped_categories''))';
comment on column public.purple_dots_calls.missing_solution_enabler_mapped_categories is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: str_list(out.get(''missing_solution_enabler_mapped_categories''))';
comment on column public.purple_dots_calls.solution_option_relevance is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: clean(out.get(''solution_option_relevance''))';
comment on column public.purple_dots_calls.solution_enablers_discussed is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(out.get(''solution_enablers_discussed''))';
comment on column public.purple_dots_calls.user_unsure_solution_options is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(out.get(''user_unsure_solution_options''))';
comment on column public.purple_dots_calls.update_profile_api_triggered is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(out.get(''update_profile_api_triggered''))';
comment on column public.purple_dots_calls.update_profile_api_successful is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(out.get(''update_profile_api_successful''))';
comment on column public.purple_dots_calls.matching_providers_found is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: whole(out.get(''matching_providers_found''))';
comment on column public.purple_dots_calls.connect_provider_api_triggered is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(out.get(''connect_provider_api_triggered''))';
comment on column public.purple_dots_calls.connect_provider_api_successful is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: yes_no(out.get(''connect_provider_api_successful''))';
comment on column public.purple_dots_calls.providers_connected is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: whole(out.get(''providers_connected''))';
comment on column public.purple_dots_calls.call_value_score is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: number(out.get(''call_value_score''))';
comment on column public.purple_dots_calls.drop_reason is
    'Raya · call_output. An AI''s summary written after the call. A claim, not a measurement, and only present when somebody answered. Expression: clean(out.get(''drop_reason''))';
comment on column public.purple_dots_calls.tools_used is
    'Raya · transcript. Dug out of the conversation''s tool calls. The profile ids live only in the arguments the bot sent to update_profile, nowhere else. Expression: str_list(out.get(''tool_accces'')) or tools_used(raw_transcript)';
comment on column public.purple_dots_calls.test_flag is
    'never filled. Declared and never populated. A query on it returns nothing, which reads as ''this never happens'' rather than ''we never asked''.';
comment on column public.purple_dots_calls.loaded_at is
    'database default. Not in the row builder at all - a serial id or a default the database supplies. Expression: -';
comment on column public.purple_dots_calls.contact_id is
    'computed locally. Derived by our code. Ours to change. Expression: str(cid) if cid is not None else None';
comment on column public.purple_dots_calls.sheet_call_id is
    'database default. Not in the row builder at all - a serial id or a default the database supplies. Expression: -';

comment on column public.purple_dots_connections.id is
    'database default. Not in the row builder at all - a serial id or a default the database supplies. Expression: -';
comment on column public.purple_dots_connections.call_id is
    'computed locally. Derived by our code. Ours to change. Expression: call_id';
comment on column public.purple_dots_connections.seeker_item_id is
    'computed locally. Derived by our code. Ours to change. Expression: clean(source.get(''item_id''))';
comment on column public.purple_dots_connections.provider_item_id is
    'computed locally. Derived by our code. Ours to change. Expression: provider';
comment on column public.purple_dots_connections.acting_as_user_id is
    'Raya · agent_args. What WE sent the bot when the batch was made. Echoed back unchanged. Expression: clean(args.get(''acting_as_user_id''))';
comment on column public.purple_dots_connections.provider_instance_url is
    'computed locally. Derived by our code. Ours to change. Expression: clean(target.get(''item_instance_url''))';
comment on column public.purple_dots_connections.consent_acknowledged is
    'computed locally. Derived by our code. Ours to change. Expression: consent.get(''acknowledged'') is True';
comment on column public.purple_dots_connections.consent_version is
    'computed locally. Derived by our code. Ours to change. Expression: whole(consent.get(''version''))';
comment on column public.purple_dots_connections.loaded_at is
    'database default. Not in the row builder at all - a serial id or a default the database supplies. Expression: -';
